apiVersion: v1
kind: Service
metadata:
  name: files-ms-internal-service
  namespace: jobster
spec:
  type: ClusterIP
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    app: filesms
    type: backend
