apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-volume-claim
  namespace: jobster
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50G
  storageClassName: manual
