apiVersion: v1
kind: Service
metadata:
  name: external-database-service
spec:
  type: NodePort
  selector:
    app: database
    type: backend
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30007
