apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobster-minio-volume
  namespace: jobster
spec:
  capacity:
    storage: 50G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/kubernetes/volumes/jobster-minio-volume"
