apiVersion: v1
kind: Service
metadata:
  name: minio-internal-service
  namespace: jobster
spec:
  type: ClusterIP
  ports:
  - name: minio9000
    targetPort: 9000
    port: 9000
  - name: minio9001
    targetPort: 9001
    port: 9001
  selector:
    app: minio
    type: backend
