apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: jobster
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30010
    name: postgresql
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
  namespace: jobster
spec:
  serviceName: "postgresql-service"
  replicas: 2
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        namespace: jobster
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          value: "N9t}OU1r^A7n"
        - name: POSTGRES_USER
          value: localdev
        - name: POSTGRES_DB
          value: jobster
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
      namespace: jobster
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 10Gi