apiVersion: v1
kind: Pod
metadata:
  name: restapi-pod
  namespace: jobster
  labels:
    app: restapi
    type: backend
spec:
  containers:
  - name: jobster-restapi
    image: ghcr.io/jobst3r/rest-backend:0.8.6
    resources:
      limits:
        memory: "2048Mi"
        cpu: "2"
      requests:
        memory: "1024Mi"
        cpu: "1"
    env:
    - name: API_PORT
      value: "3333"
    - name: DATABASE_URL
      value: postgres://localdev:N9t}OU1r^A7n@172.20.0.2:5432/jobster
    - name: DB_HOST
      value: 172.20.0.2
    - name: DB_HOST
      value: 172.20.0.2
    - name: DB_PASSWORD
      value: N9t}OU1r^A7n
    - name: DB_PORT
      value: "5432"
    - name: DB_USER
      value: localdev
    - name: SECURITY_JWT_SECRET
      value: oklasjflkasf9009!gjasjgalksjgl
    - name: TEST
      value: "FALSE"
    - name: MINIO_HOST
      value: 172.20.0.4
    - name: MINIO_PORT
      value: "9000"
    - name: MINIO_ACCESS_KEY
      value: minioadmin
    - name: MINIO_SECRET_KEY
      value: minioadmin
