apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - postgresql-deployment.yml
  - postgresql-internal-service.yml
  - postgresql-external-service.yml
  - postgresql-secret.yml
  - postgresql-volume.yml
  - postgresql-volumeclaim.yml