apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: infra
  labels:
    app: postgresql
type: Opaque
data:
  username: "bG9jYWxkZXY="
  password: "Tjl0fU9VMXJeQTdu"
  database: "am9ic3Rlcg=="