apiVersion: v1
kind: Service
metadata:
  name: external-postgresql-service
  namespace: infra
spec:
  type: NodePort
  selector:
    app: postgresql
    type: backend
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30008
