apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: infra
  labels:
    app: postgresql
type: Opaque
data:
  username: "localdev"
  password: "N9t}OU1r^A7n"
  database: "jobster"