apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobster-postgresql-volume
  namespace: jobster
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/kubernetes/volumes/jobster-db-volume"
