apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: infra
  labels:
    app: postgresql
    type: backend

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
        type: backend
    spec:
      containers:
      - name: jobster-postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "8192Mi"
            cpu: "4"
          requests:
            memory: "2048Mi"
            cpu: "2"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data-volume
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: database
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: postgresql-volume-claim
  selector:
    matchLabels:
      app: postgresql
      type: backend



