apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/kubernetes/volumes/postgresql-volume"
