apiVersion: v1
kind: ConfigMap
metadata:
  name: searches-ms-configmap
  namespace: jobster
data:
  API_PORT: "7777"
  DB_HOST: internal-postgresql-service.infra
  DB_PASSWORD: N9t}OU1r^A7n
  DB_PORT: "5432"
  DB_USER: localdev
