apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
  namespace: infra
spec:
  capacity:
    storage: 50G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/kubernetes/volumes/minio-volume"
