apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-acme-crt
  namespace: argocd
spec:
  secretName: argocd-cert
  dnsNames:
  - argocd.jobster.francois-egner.de
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
