apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: jobster
  labels:
    app: database
    type: backend

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
        type: backend
    spec:
      containers:
      - name: jobster-database
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "8192Mi"
            cpu: "4"
          requests:
            memory: "2048Mi"
            cpu: "2"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume
        env:
        - name: POSTGRES_PASSWORD
          value: "N9t}OU1r^A7n"
        - name: POSTGRES_USER
          value: localdev
        - name: POSTGRES_DB
          value: jobster
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: database-volume-claim
  selector:
    matchLabels:
      app: database
      type: backend



