apiVersion: v1
kind: Service
metadata:
  name: restapi-internal-service
  namespace: jobster
spec:
  type: ClusterIP
  ports:
  - targetPort: 3333
    port: 3333
  selector:
    app: restapi
    type: backend
