apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
  namespace: jobster
  labels:
    app: restapi
    type: backend

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: restapi
        type: backend
    spec:
      containers:
      - name: jobster-restapi
        image: ghcr.io/jobst3r/rest-backend:0.8.6
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2"
          requests:
            memory: "1024Mi"
            cpu: "1"
        env:
        - name: API_PORT
          value: "3333"
        - name: DATABASE_URL
          value: postgres://localdev:N9t}OU1r^A7n@database-service:5432/jobster
        - name: DB_HOST
          value: database-service
        - name: DB_PASSWORD
          value: "N9t}OU1r^A7n"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: localdev
        - name: SECURITY_JWT_SECRET
          value: oklasjflkasf9009!gjasjgalksjgl
        - name: TEST
          value: "FALSE"
        - name: MINIO_HOST
          value: minio-internal-service
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: 2k46Tr@VpV9GBFhy
      imagePullSecrets:
      - name: github-registry-secret
  selector:
    matchLabels:
      app: restapi
      type: backend



